algoritmo "Nome do Programa"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
var
contador: inteiro


inicio

    enquanto (contador <= 100) faca
    escreval ("one pice is real",contador,"vezes")
    contador <- contador + 1
    fimenquanto

fimalgoritmo